name: Generate PlantUML Diagrams

on:
  push:
    paths:
      - '**.puml'
      - '.github/workflows/plantuml.yml'
  pull_request:
    paths:
      - '**.puml'
      - '.github/workflows/plantuml.yml'

jobs:
  plantuml:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get changed UML files
        id: getfile
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | grep '\.puml$' | xargs)" >> $GITHUB_OUTPUT

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg ${{ steps.getfile.outputs.files }}

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Generate SVG files for PlantUML diagrams"
          branch: ${{ github.head_ref }}
